#---- begin snakebids boilerplate ----------------------------------------------

from snakebids import bids, generate_inputs, get_wildcard_constraints
import os

configfile: workflow.source_path('../config/snakebids.yml')

# Get input wildcards
inputs = generate_inputs(
    bids_dir=config["bids_dir"],
    pybids_inputs=config["pybids_inputs"],
    pybidsdb_dir=config.get("pybidsdb_dir"),
    pybidsdb_reset=config.get("pybidsdb_reset"),
    derivatives=config.get("derivatives", None),
    participant_label=config.get("participant_label", None),
    exclude_participant_label=config.get("exclude_participant_label", None),
    validate=not config.get("plugins.validator.skip", False),
    pybids_config=workflow.source_path("../config/bids.json")
)

#this adds constraints to the bids naming
wildcard_constraints:  **get_wildcard_constraints(config['pybids_inputs'])

#---- end snakebids boilerplate ------------------------------------------------

rule samplevolume:
    input: 
        volume = inputs['volume'].path,
        inner = inputs['inner'].path,
        outer = inputs['outer'].path,
        midthickness = inputs['mid'].path,
    output:
        bids(
            root=config['root'],
            datatype='surf',
            hemi = '{hemi}',
            den = '{den}',
            label = '{label}',
            extension='.shape.gii',
            **inputs['volume'].wildcards
        )
    container: config['singularity']['connectome_workbench']
    log:
        bids(
            root='logs',
            hemi = '{hemi}',
            den = '{den}',
            label = '{label}',
            extension='.log',
            **inputs['volume'].wildcards
        )
    shell: 'wb_command -volume-to-surface-mapping {input.volume} {input.midthickness} {output} -cubic -ribbon-constrained {input.inner} {input.outer} -gaussian '

rule all:
    input:
        inputs['mid'].expand(
            inputs['volume'].expand(
                rules.samplevolume.output,
                allow_missing=True

                # suffix = input['volume'].suffix,
            )
        )
    default_target: True
