#---- begin snakebids boilerplate ----------------------------------------------

from snakebids import bids, generate_inputs, get_wildcard_constraints
import os

print(os.getcwd())
print(os.listdir('..'))

configfile: workflow.source_path('../config/snakebids.yml')

# Get input wildcards
inputs = generate_inputs(
    bids_dir=config["bids_dir"],
    pybids_inputs=config["pybids_inputs"],
    pybidsdb_dir=config.get("pybidsdb_dir"),
    pybidsdb_reset=config.get("pybidsdb_reset"),
    derivatives=config.get("derivatives", None),
    participant_label=config.get("participant_label", None),
    exclude_participant_label=config.get("exclude_participant_label", None),
    validate=not config.get("plugins.validator.skip", False)
)

#this adds constraints to the bids naming
wildcard_constraints:  **get_wildcard_constraints(config['pybids_inputs'])

#---- end snakebids boilerplate ------------------------------------------------


rule samplevolume:
    input: 
        volume = inputs['volume'].path,
        inner = inputs['volume'].path,
        outer = inputs['volume'].path,
        midthickness = inputs['volume'].path,
    output:
        bids(
            root=config['root'],
            datatype='surf',
            desc='smooth{fwhm}mm',
            suffix='bold',
            extension='.nii.gz'
            **inputs['bold'].wildcards
        )
    container: config['singularity']['connectome_workbench']
    log:
        bids(
            root='logs',
            suffix='samplevolume.log',
            fwhm='{fwhm}',
            **inputs['bold'].wildcards
        )
    params: sigma = lambda wildcards: f'{float(wildcards.fwhm)/2.355:0.2f}'
    shell: 'wb_command -volume-to-surface-mapping {input.volume} {input.midthickness} {output} -cubic -ribbon-constrained {input.inner} {input.outer} -gaussian '


rule all:
    input:
        inputs['bold'].expand(
            rules.samplevolume.output,
            fwhm = config['smoothing_fwhm'],
        )
    default_target: True
